package ejercicio02_KioskoNoTradicional;

import javax.swing.JOptionPane;

/**
 *
 * @author Javier "KuaKer" Suárez Guzmán
 */
public class KioskoNoTradicional extends javax.swing.JFrame {

    /**
     * Creates new form KioskoNoTradicional
     */
    public KioskoNoTradicional() {
        initComponents();
        this.setLocationRelativeTo(this);
        txtCantidad.setText("1");
        jTextPane1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoPreparacion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        panelAgregados = new javax.swing.JPanel();
        chbMayo = new javax.swing.JCheckBox();
        chbKetchup = new javax.swing.JCheckBox();
        chbMostaza = new javax.swing.JCheckBox();
        chbAmericana = new javax.swing.JCheckBox();
        chbTomate = new javax.swing.JCheckBox();
        chbPalta = new javax.swing.JCheckBox();
        chbChucrut = new javax.swing.JCheckBox();
        panelBotones = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTamaño = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        panelPreparacion = new javax.swing.JPanel();
        rbtCompleto = new javax.swing.JRadioButton();
        rbtChurrasco = new javax.swing.JRadioButton();
        rbtPizza = new javax.swing.JRadioButton();
        cbBebida = new javax.swing.JComboBox<>();
        panelAgregadosPizza = new javax.swing.JPanel();
        chbQueso = new javax.swing.JCheckBox();
        chbSeitan = new javax.swing.JCheckBox();
        chbHeura = new javax.swing.JCheckBox();
        chbChoclo = new javax.swing.JCheckBox();
        chbCebolla = new javax.swing.JCheckBox();
        chbAlcachofa = new javax.swing.JCheckBox();
        txtCantidad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cantidad");

        panelAgregados.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregados"));

        chbMayo.setText("Mayo + $200");
        chbMayo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbMayo.setMultiClickThreshhold(3L);
        chbMayo.setPreferredSize(null);

        chbKetchup.setText("Kétchup");
        chbKetchup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbKetchup.setMultiClickThreshhold(3L);
        chbKetchup.setPreferredSize(null);

        chbMostaza.setText("Mostaza");
        chbMostaza.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbMostaza.setMultiClickThreshhold(3L);
        chbMostaza.setPreferredSize(null);

        chbAmericana.setText("Americana + $200");
        chbAmericana.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbAmericana.setMultiClickThreshhold(3L);
        chbAmericana.setPreferredSize(null);

        chbTomate.setText("Tomate + $200");
        chbTomate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbTomate.setMultiClickThreshhold(3L);

        chbPalta.setText("Palta + $300");
        chbPalta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbPalta.setMultiClickThreshhold(3L);

        chbChucrut.setText("Chucrut + $200");
        chbChucrut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbChucrut.setMultiClickThreshhold(3L);
        chbChucrut.setPreferredSize(null);

        javax.swing.GroupLayout panelAgregadosLayout = new javax.swing.GroupLayout(panelAgregados);
        panelAgregados.setLayout(panelAgregadosLayout);
        panelAgregadosLayout.setHorizontalGroup(
            panelAgregadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chbMostaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbKetchup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbMayo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbTomate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbPalta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbChucrut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbAmericana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAgregadosLayout.setVerticalGroup(
            panelAgregadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbMayo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbAmericana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbTomate)
                .addGap(18, 18, 18)
                .addComponent(chbPalta)
                .addGap(18, 18, 18)
                .addComponent(chbChucrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo pedido");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Total a pagar"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setText("Tamaño");

        cbTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chica $0.-", "Mediana $500.-", "Grande $1.000.-" }));

        jLabel4.setText("Para beber");

        panelPreparacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de preparación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        grupoTipoPreparacion.add(rbtCompleto);
        rbtCompleto.setText("Completo");
        rbtCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCompletoActionPerformed(evt);
            }
        });

        grupoTipoPreparacion.add(rbtChurrasco);
        rbtChurrasco.setText("Churrasco");
        rbtChurrasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtChurrascoActionPerformed(evt);
            }
        });

        grupoTipoPreparacion.add(rbtPizza);
        rbtPizza.setText("Pizza");
        rbtPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPreparacionLayout = new javax.swing.GroupLayout(panelPreparacion);
        panelPreparacion.setLayout(panelPreparacionLayout);
        panelPreparacionLayout.setHorizontalGroup(
            panelPreparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreparacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtCompleto)
                .addGap(44, 44, 44)
                .addComponent(rbtChurrasco, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(rbtPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelPreparacionLayout.setVerticalGroup(
            panelPreparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreparacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPreparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtCompleto)
                    .addComponent(rbtChurrasco)
                    .addComponent(rbtPizza))
                .addContainerGap())
        );

        cbBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Bebida en lata $800.-", "Jugo natural $800.-", "Café $800.-", "Té $500.-" }));

        panelAgregadosPizza.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregados Pizza"));

        chbQueso.setText("Extra queso + $500");
        chbQueso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbQueso.setMultiClickThreshhold(3L);

        chbSeitan.setText("Seitán + $1.000");
        chbSeitan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbSeitan.setMultiClickThreshhold(3L);
        chbSeitan.setPreferredSize(null);

        chbHeura.setText("Heüra + $1.200");
        chbHeura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbHeura.setMultiClickThreshhold(3L);
        chbHeura.setPreferredSize(null);

        chbChoclo.setText("Choclo + $500");
        chbChoclo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbChoclo.setMultiClickThreshhold(3L);
        chbChoclo.setPreferredSize(null);

        chbCebolla.setText("Cebolla + $700");
        chbCebolla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbCebolla.setMultiClickThreshhold(3L);
        chbCebolla.setPreferredSize(null);

        chbAlcachofa.setText("Fondos de alcachofa + $800");
        chbAlcachofa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chbAlcachofa.setMultiClickThreshhold(3L);
        chbAlcachofa.setPreferredSize(null);

        javax.swing.GroupLayout panelAgregadosPizzaLayout = new javax.swing.GroupLayout(panelAgregadosPizza);
        panelAgregadosPizza.setLayout(panelAgregadosPizzaLayout);
        panelAgregadosPizzaLayout.setHorizontalGroup(
            panelAgregadosPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregadosPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgregadosPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chbAlcachofa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbCebolla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbQueso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbSeitan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbHeura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chbChoclo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAgregadosPizzaLayout.setVerticalGroup(
            panelAgregadosPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregadosPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chbQueso)
                .addGap(18, 18, 18)
                .addComponent(chbSeitan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbHeura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbChoclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbCebolla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbAlcachofa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de la compra"));

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(cbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(panelAgregadosPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(panelPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(cbTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAgregadosPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        calcularPresupuesto(1);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        calcularPresupuesto(2);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        grupoTipoPreparacion.clearSelection();
        txtCantidad.setText("1");
        cbTamaño.setSelectedIndex(0);
        cbBebida.setSelectedIndex(0);
        //agregados completos y churrascos
        chbMayo.setSelected(false);
        chbMayo.setEnabled(true);
        chbKetchup.setSelected(false);
        chbKetchup.setEnabled(true);
        chbMostaza.setSelected(false);
        chbMostaza.setEnabled(true);
        chbAmericana.setSelected(false);
        chbAmericana.setEnabled(true);
        chbTomate.setSelected(false);
        chbTomate.setEnabled(true);
        chbPalta.setSelected(false);
        chbPalta.setEnabled(true);
        chbChucrut.setSelected(false);
        chbChucrut.setEnabled(true);
        //agregados pizza
        chbQueso.setSelected(false);
        chbQueso.setEnabled(true);
        chbSeitan.setSelected(false);
        chbSeitan.setEnabled(true);
        chbHeura.setSelected(false);
        chbHeura.setEnabled(true);
        chbChoclo.setSelected(false);
        chbChoclo.setEnabled(true);
        chbCebolla.setSelected(false);
        chbCebolla.setEnabled(true);
        chbAlcachofa.setSelected(false);
        chbAlcachofa.setEnabled(true);
        //paneles
        jLabel2.setText("");
        jTextPane1.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        grupoTipoPreparacion.clearSelection();
        txtCantidad.setText("1");
        cbTamaño.setSelectedIndex(0);
        cbBebida.setSelectedIndex(0);
        //agregados completos y churrascos
        chbMayo.setSelected(false);
        chbMayo.setEnabled(true);
        chbKetchup.setSelected(false);
        chbKetchup.setEnabled(true);
        chbMostaza.setSelected(false);
        chbMostaza.setEnabled(true);
        chbAmericana.setSelected(false);
        chbAmericana.setEnabled(true);
        chbTomate.setSelected(false);
        chbTomate.setEnabled(true);
        chbPalta.setSelected(false);
        chbPalta.setEnabled(true);
        chbChucrut.setSelected(false);
        chbChucrut.setEnabled(true);
        //agregados pizza
        chbQueso.setSelected(false);
        chbQueso.setEnabled(true);
        chbSeitan.setSelected(false);
        chbSeitan.setEnabled(true);
        chbHeura.setSelected(false);
        chbHeura.setEnabled(true);
        chbChoclo.setSelected(false);
        chbChoclo.setEnabled(true);
        chbCebolla.setSelected(false);
        chbCebolla.setEnabled(true);
        chbAlcachofa.setSelected(false);
        chbAlcachofa.setEnabled(true);
        //paneles
        jLabel2.setText("");
        jTextPane1.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rbtCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCompletoActionPerformed
        chbMayo.setEnabled(true);
        chbKetchup.setEnabled(true);
        chbMostaza.setEnabled(true);
        chbAmericana.setEnabled(true);
        chbTomate.setEnabled(true);
        chbPalta.setEnabled(true);
        chbChucrut.setEnabled(true);
        //desactivando agregados pizza
        chbQueso.setEnabled(false);
        chbQueso.setSelected(false);
        chbSeitan.setEnabled(false);
        chbSeitan.setSelected(false);
        chbHeura.setEnabled(false);
        chbHeura.setSelected(false);
        chbChoclo.setEnabled(false);
        chbChoclo.setSelected(false);
        chbCebolla.setEnabled(false);
        chbCebolla.setSelected(false);
        chbAlcachofa.setEnabled(false);
        chbAlcachofa.setSelected(false);
    }//GEN-LAST:event_rbtCompletoActionPerformed

    private void rbtChurrascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtChurrascoActionPerformed
        chbMayo.setEnabled(true);
        chbKetchup.setEnabled(true);
        chbMostaza.setEnabled(true);
        chbAmericana.setEnabled(true);
        chbTomate.setEnabled(true);
        chbPalta.setEnabled(true);
        chbChucrut.setEnabled(true);
        //desactivando agregados pizza
        chbQueso.setEnabled(false);
        chbQueso.setSelected(false);
        chbSeitan.setEnabled(false);
        chbSeitan.setSelected(false);
        chbHeura.setEnabled(false);
        chbHeura.setSelected(false);
        chbChoclo.setEnabled(false);
        chbChoclo.setSelected(false);
        chbCebolla.setEnabled(false);
        chbCebolla.setSelected(false);
        chbAlcachofa.setEnabled(false);
        chbAlcachofa.setSelected(false);
    }//GEN-LAST:event_rbtChurrascoActionPerformed

    private void rbtPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPizzaActionPerformed
        chbMayo.setEnabled(false);
        chbMayo.setSelected(false);
        chbKetchup.setEnabled(false);
        chbKetchup.setSelected(false);
        chbMostaza.setEnabled(false);
        chbMostaza.setSelected(false);
        chbAmericana.setEnabled(false);
        chbAmericana.setSelected(false);
        chbTomate.setEnabled(false);
        chbTomate.setSelected(false);
        chbPalta.setEnabled(false);
        chbPalta.setSelected(false);
        chbChucrut.setEnabled(false);
        chbChucrut.setSelected(false);
        //desactivando agregados completos y churrascos
        chbQueso.setEnabled(true);
        chbSeitan.setEnabled(true);
        chbHeura.setEnabled(true);
        chbChoclo.setEnabled(true);
        chbCebolla.setEnabled(true);
        chbAlcachofa.setEnabled(true);
    }//GEN-LAST:event_rbtPizzaActionPerformed

    public void calcularPresupuesto(int opcion) {
        int cantidad = Integer. parseInt(txtCantidad.getText());
        int aPagar = 0;
        boolean swTipoPreparacion = true, swBebida = true;
        String mensajeError = "Debe seleccionar:\n";
        String detalle = "Detalle de la compra\n";
        
        if (rbtCompleto.isSelected()) {
            aPagar += 1000;
            detalle += "Completo: $ 1.000.- \n";
            swTipoPreparacion = false;
        } else {
            if (rbtChurrasco.isSelected()) {
                aPagar = +1500;
                detalle += "Churrasco: $ 1.500.- \n";
                swTipoPreparacion = false;
            } else {
                if (rbtPizza.isSelected()) {
                    aPagar += 2000;
                    detalle += "Pizza: $ 2.000.- \n";
                    swTipoPreparacion = false;
                } else {
                    // NO HA SELECCIONADO OPCIÓN
                    mensajeError += " - Tipo de preparación\n";
                }
            }
        }
        //verificando tamaño
        int posItem = cbTamaño.getSelectedIndex();
        if (posItem >= 0) {
            switch (posItem) {
                case 0: // Chica
                    aPagar += 0;
                    detalle += "Tamaño chica: $ 0.- \n";
                    break;
                case 1: // Mediana
                    aPagar += 500;
                    detalle += "Tamaño mediana: $ 500.- \n";
                    break;
                case 2: // Grande
                    aPagar += 1000;
                    detalle += "Tamaño grande: $ 1.000.- \n";
                    break;
            }
        }
        //verificando bebida
        int posItem2 = cbBebida.getSelectedIndex();
        if (posItem2 > 0) {
            swBebida = false;
            switch (posItem2) {
                case 1: //bebida lata
                    aPagar += 800;
                    detalle += "Bebida en lata: $ 800.- \n";
                    break;
                case 2:
                    aPagar += 800;
                    detalle += "Jugo natural: $ 800.- \n";
                    break;
                case 3:
                    aPagar += 800;
                    detalle += "Café: $ 800.- \n";
                    break;
                case 4:
                    aPagar += 500;
                    detalle += "Té: $ 500.- \n";
                    break;
            }
        } else {
            mensajeError += " - Un bebestible\n";
        }        
        //verificando agregados pizza
        if (chbQueso.isSelected()) {
            aPagar += 500;
            detalle += "Extra queso: $500\n";
        }
        if (chbSeitan.isSelected()) {
            aPagar += 1000;
            detalle += "Seitán: $1.000\n";
        }
        if (chbHeura.isSelected()) {
            aPagar += 1200;
            detalle += "Heüra: $1.200\n";
        }
        if (chbChoclo.isSelected()) {
            aPagar += 500;
            detalle += "Choclo: $500\n";
        }
        if (chbCebolla.isSelected()) {
            aPagar += 700;
            detalle += "Cebolla: $700\n";
        }
        if (chbAlcachofa.isSelected()) {
            aPagar += 800;
            detalle += "Fondos de alcachofa: $800\n";
        }
        //verificando agregados completo & churrasco
        if (chbMayo.isSelected()) {
            aPagar += 200;
            detalle += "Mayonesa: $200\n";
        }
        if (chbKetchup.isSelected()) {
            aPagar += 0;
            detalle += "Kétchup\n";
        }
        if (chbMostaza.isSelected()) {
            aPagar += 0;
            detalle += "Mostaza\n";
        }
        if (chbAmericana.isSelected()) {
            aPagar += 200;
            detalle += "Americana: $200\n";
        }
        if (chbTomate.isSelected()) {
            aPagar += 200;
            detalle += "Tomate: $200\n";
        }
        if (chbPalta.isSelected()) {
            aPagar += 300;
            detalle += "Palta: $300\n";
        }
        if (chbChucrut.isSelected()) {
            aPagar += 200;
            detalle += "Chucrut: $200\n";
        }

        detalle += "\nCantidad: "+cantidad+"\n$ " + (aPagar*cantidad) + " - Total compra\n";
        if (swTipoPreparacion || swBebida) {
            JOptionPane.showMessageDialog(null, mensajeError);
        } else {
            if (opcion == 1) {
                //JOptionPane.showMessageDialog(null, "Valor a Pagar $ " + aPagar + ".-");
                jLabel2.setText("Valor a Pagar $ " + (aPagar*cantidad) + ".-");
            }
            if (opcion == 2) {
                //JOptionPane.showMessageDialog(null, detalle);
                jTextPane1.setText(detalle);
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KioskoNoTradicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KioskoNoTradicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KioskoNoTradicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KioskoNoTradicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KioskoNoTradicional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbBebida;
    private javax.swing.JComboBox<String> cbTamaño;
    private javax.swing.JCheckBox chbAlcachofa;
    private javax.swing.JCheckBox chbAmericana;
    private javax.swing.JCheckBox chbCebolla;
    private javax.swing.JCheckBox chbChoclo;
    private javax.swing.JCheckBox chbChucrut;
    private javax.swing.JCheckBox chbHeura;
    private javax.swing.JCheckBox chbKetchup;
    private javax.swing.JCheckBox chbMayo;
    private javax.swing.JCheckBox chbMostaza;
    private javax.swing.JCheckBox chbPalta;
    private javax.swing.JCheckBox chbQueso;
    private javax.swing.JCheckBox chbSeitan;
    private javax.swing.JCheckBox chbTomate;
    private javax.swing.ButtonGroup grupoTipoPreparacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel panelAgregados;
    private javax.swing.JPanel panelAgregadosPizza;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelPreparacion;
    private javax.swing.JRadioButton rbtChurrasco;
    private javax.swing.JRadioButton rbtCompleto;
    private javax.swing.JRadioButton rbtPizza;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
